// Array file for demographics

export const gender: Array<string> = [
    "Male",
    "Female"
];

export const racialEthnicIdentity: Array<string> = [
    "American Indian or Alaska Native",
    "Asian Indian",
    "Black or African American (Hispanic or Latino)",
    "Black or African American (non-Hispanic or Latino)",
    "Cambodian",
    "Chinese",
    "Filipino",
    "Guamanian",
    "Hmong",
    "Indigenous - Latin American",
    "Japanese",
    "Korean",
    "Laotian",
    "Native Hawaiian",
    "Vietnamese",
    "Other Asian",
    "Thai",
    "Samoan",
    "White (Hispanic or Latino)",
    "White (non-Hispanic or Latino)",
    "Hispanic or Latino (any other race)",
    "Other"
];

export const serviceLanguages: Array<string> = [
    "English",
    "Spanish",
    "American Sign Language",
    "Amharic",
    "Arabic",
    "Armenian",
    "Assyrian",
    "Bengali",
    "Burmese",
    "Cambodian",
    "Cantonese",
    "Farsi",
    "French",
    "Gujarati",
    "Hebrew",
    "Hindi",
    "Hmong",
    "Ilocano",
    "Italian",
    "Japanese",
    "Kanjobal",
    "Korean",
    "Lao",
    "Mam",
    "Mandarin",
    "Mien",
    "Mixteco",
    "Pashtu",
    "Polish",
    "Portuguese",
    "Punjabi",
    "Romanian",
    "Russian",
    "Samoan",
    "Togalog",
    "Thai",
    "Tigrigna",
    "Turkic",
    "Turkish",
    "Triqui",
    "Urdu",
    "Vietnamese",
    "Zapoteco",
    "Other Chinese Languages",
    "Other Non-English",
    "Other Sign Language"
];

export const countryOfOrigin: Array<string> = [
    "Afghanistan",
    "Argentina",
    "Armenia",
    "Bangladesh",
    "Brazil",
    "Cambodia",
    "China, People's Republic",
    "Colombia",
    "Ecuador",
    "Egypt",
    "El Salvador",
    "Ethiopia",
    "Guatemala",
    "Honduras",
    "India",
    "Indonesia",
    "Iran",
    "Iraq",
    "Japan",
    "Korea, South",
    "Laos",
    "Malaysia",
    "Mexico",
    "Myanmar",
    "Nepal",
    "Nicaragua",
    "Pakistan",
    "Peru",
    "Philippines",
    "Russia",
    "Taiwan",
    "Thailand",
    "Ukraine",
    "Vietnam",
    "Other"
];

export const sexualOrientation: Array<string> = [
    "Straight or heterosexual",
    "Bisexual",
    "Gay or Lesbian",
    "Queer",
    "Another sexual orientation",
    "Unknown",
    "Decline to state"
];

export const age: Array<string> = [
    "Youth (0- 14 years old)",
    "Young (15-17 years old)",
    "Young Adults (18-30 years old)",
    "Adults (31-49 years old)",
    "Adults (50-64 years old)",
    "Adults (65+ years old)"
];

export const educationLevel: Array<string> = [
    "None or did not complete primary school",
    "Completed primary school",
    "Completed secondary school",
    "Some college",
    "Completed college",
    "Completed graduate school",
    "Unknown"
];

export const countyOfResidence: Array<string> = [
    "Alameda",
    "Alpine",
    "Amador",
    "Butte",
    "Calaveras",
    "Colusa",
    "Contra Costa",
    "Del Norte",
    "El Dorado",
    "Fresno",
    "Glenn",
    "Humboldt",
    "Imperial",
    "Inyo",
    "Kern",
    "Kings",
    "Lake",
    "Lassen",
    "Los Angeles",
    "Madera",
    "Marin",
    "Mariposa",
    "Mendocino",
    "Merced",
    "Modoc",
    "Mono",
    "Monterey",
    "Napa",
    "Nevada",
    "Orange",
    "Placer",
    "Plumas",
    "Riverside",
    "Sacramento",
    "San Benito",
    "San Bernardino",
    "San Diego",
    "San Francisco",
    "San Joaquin",  
    "San Luis Obispo",
    "San Mateo",
    "Santa Barbara",
    "Santa Clara",
    "Santa Cruz",
    "Shasta",
    "Sierra",
    "Siskiyou",
    "Solano",
    "Sonoma",
    "Stanislaus",
    "Sutter",
    "Tehama",
    "Trinity",
    "Tulare",
    "Tuolumne",
    "Ventura",
    "Yolo",
    "Yuba"
];