export const processes: Array<string> = [
    "Legal Consultation",
    "App. For Perm. Res. Card",
    "RFE",
    "NOID",
    "Initial Application",
    "Renewal Application",
    "Naturalization Certificate",
    "Citizenship Certificate",
    "FOIA Request",
    "Criminal Record Reeview",
    "Refugee Relative",
    "Asylee Relative",
    "Application for Certificate of Naturalization",
    "Legal Rep. at USCIS Interview",
    "DACA",
    "Naturalization",
    "Removal of Conditions",
    "Advance Parole",
    "Parole in Place",
    "Humanitarian Parole",
    "TPS w/ EAD",
    "Petition by US Citizen",
    "Petition by LPR in CA",
    "DACA w/ Criminal History",
    "DACA w/ appeal(s)",
    "Natz w/ Criminal History",
    "Natz w/ Appeal(s)",
    "Natz w/ Medical Waiver",
    "Asylum",
    "U-VISA",
    "T-VISA",
    "VAWA",
    "SIJS",
    "AOS",
    "One-Step AOS",
    "Provisional Unlawful"
];